### ISSUE TITLE
Stuck at Logging In...

### ISSUE THREAD

**Issue by waseltzer** [SeaPea/HomeP#1]
HomeP stopped working. The watchface is stuck at "Logging In."
Checked username/password -- that's not the problem.
What could be wrong?
Thanks,
Wayne

**Comment by SeaPea** [comment]
That usually means that the Pebble phone app has crashed or froze, but I think they may have finally retired the old API that the app relies on as I can login, but cannot get the status of my garage door.

**Comment by waseltzer** [comment]
Strange. It worked again today, and then stopped working again.

Any possibility of fixing this problem?  Is there an alternative to whatever Pebble service is no longer working correctly? 

Thanks,
Wayne

**Comment by SeaPea** [comment]
I fixed the API calls yesterday. You should make sure you have v2.3. I think they had a general server issue tonight, but now it is all working again.

**Comment by waseltzer** [comment]
Working again. Thanks so much! Really appreciate this app.
(I use it to open my garage door from my bicycle.)

**Comment by waseltzer** [comment]
I bought a new phone (Google Pixel 3) and I can't get HomeP (v 2.5)  to work now.
Stuck at "Logging in..." again.
I'm sure I've entered the correct MyQ username/password in the HomeP settings.

"My Chamberlain" app is working fine on this phone.

Ideas?

Thanks,
Wayne
